<?php

return [
    'department' => [
        'table_22_' => "Akademik almashuv dasturlarda ishtirok etuvchi talabalar soni",
        'table_23_' => "Yetakchi xorijiy mamlakatlarning ta’lim muassasalaridan taklif etilib, dars berayotgan xorijiy o‘qituvchilar",
        'table_24_' => "Talabalarning Scopus, Web of Science bazalaridagi maqolalari",
    ],
    'employee' => [
        'table_2_' => "Dunyoning nufuzli 1000 taligiga kirgan xorijiy OTMlarda Phd/DSc ilmiy darajasini olganligi",
        'table_3_' => "Dunyoning nufuzli 500 taligiga kirgan xorijiy OTMlarda magistratura bosqichida tahsil olganligi",
        'table_4_' => "Darslik",
        'table_5_' => "O'quv qo'llanma",
        'table_6_' => "Dunyoning nufuzli 1000 taligiga kirgan xorijiy OTMlarda o‘quv mashg‘ulotlari (ma’ruzalar, amaliy mashg‘ulotlar, seminarlar) o‘tkazganligi",
        'table_7_' => "So‘nggi uch yilda xorijiy TOP-1000 OTMlarda (yoki Coursera, Udemy, EdX kabi ta’lim platformalarida) mutaxassisligi bo'yicha malaka oshirish kurslaridan o‘tganligi ",
        'table_8_1_' => "Xorijiy tillarni bilish darajasini aniqlovchi sertifikatlari (kamida B2; xorijiy til o'qituvchisi uchun C1)",
        'table_8_2_' => "Mutaxassisligi bo'yicha xorijiy til (ingliz tili)da dars berganligi",
        'table_9_1_' => "Monografiya (Scopus, Web of Science bazalarida indekslangan)",
        'table_9_2_' => "Monografiya (Mahalliy nashriyotlarda)",
        'table_10_1_' => "Q1-Q2 holatida Scopus, Web of Science bazalarida indekslangan maqola",
        'table_10_2_' => "Q3 holatida Scopus, Web of Science bazalarida indekslangan maqola",
        'table_10_3_' => "Q4 holatida Scopus, Web of Science bazalarida indekslangan maqola yoki Scopus, Web of Science bazalarida indekslangan konferensiyada tezis",
        'table_11_1_' => "Scopus, Web of Sicence bazalaridagi iqtibosga egalik",
        'table_11_2_' => "ResearchGate platformasidagi iqtibosga egalik",
        'table_11_3_' => "Google Scholar plarformasidagi iqtibosga egalik",
        'table_12_' => "OAK ro'yxatidagi xorijiy ilmiy jurnallarda maqola",
        'table_13_' => "OAK ro'yxatidagi mahalliy ilmiy jurnallarda maqola",      
        'table_14_1_' => "Professor-o'qituvchining xalqaro konferensiya va seminarlarda, ilmiy yoki ta’lim loyihalarida (xorijiy, qo‘shma) ma'ruzachi sifatida ishtirok etganligi",
        'table_14_2_' => "Professor-o'qituvchining xalqaro konferensiya va seminarlarda, ilmiy yoki ta’lim loyihalarida (xorijiy, qo‘shma) ishtirok etganligi",
        'table_14_3_' => "Talabalarning xalqaro konferensiya va seminarlarda, ilmiy yoki ta’lim loyihalarida (xorijiy, qo‘shma) ishtirok etganligi (bir PO'ga 10 talaba))",        
        'table_15_1_' => "Xalqaro va mahalliy ilmiy (amaliy, innovatsion va fundamental) loyihalar: rahbarlik qilish",
        'table_15_2_' => "Xalqaro va mahalliy ilmiy (amaliy, innovatsion va fundamental) loyihalar: ishtirok etish",
        'table_16_' => "Xo‘jalik shartnomalarida ishtirok etish (professsor-o‘qituvchiga belgilangan rejaning 100 % - 2 mln so'm bajarilganda)",
        'table_17_1_' => "Ixtirolar, patentlar",
        'table_17_2_' => "Axborot-kommunikatsiya texnologiyalariga oid dasturlar va elektron bazalari uchun olingan guvohnomalar, mualliflik huquqi bilan himoya qilinadigan turli materiallar",
          // Yangi yaratish kerak.
        'table_18_1_' => "Professor",
        'table_18_2_' => "Fan doktori (DSc)",
        'table_18_3_' => "Dotsent",
        'table_18_3_a_' => "Fan nomzodi / Falsafa doktori (PhD)",
        'table_19_' => "Hisob yilida (2025) PhD/DSc ilmiy daraja (shu jumladan, berilgan professor yoki dotsent ilmiy unvoni) olganligi",
        'table_20_1_' => "Xalqaro/Respublika miqyosda Radio efir/TV/ommabop gazeta yoki jurnalda universitet nomidan chiqish",
        'table_20_2_' => "Viloyat miqyosda Radio efir/TV/ommabop gazeta yoki jurnalda universitet nomidan chiqish",
        'table_20_3_' => "Tuman/shahar miqyosda Radio efir/TV/ommabop gazeta yoki jurnalda universitet nomidan chiqish",
        'table_21_1_' => "Professor-o‘qituvchining nufuzli xalqaro tanlovlarda sovrinli o'rinlarni qo'lgan kiritganligi yoki uning rahbarligida xalqaro olimpiadalarda va nufuzli tanlovlarda sovrinli o‘rinlarni qo‘lga kiritgan va mukofot (diplom)larga sozovor bo‘lgan hamda O‘zbekiston Respublikasi Prezidenti davlat stipendiyasi sovrindorlari bo‘lgan talabalar",
        'table_21_2_' => "Professor-o‘qituvchining nufuzli Respublika tanlovlarida sovrinli o'rinlarni qo'lgan kiritganligi yoki uning rahbarligida Respublika olimpiadalarda va nufuzli tanlovlarda sovrinli o‘rinlarni qo‘lga kiritgan va mukofot (diplom)larga sazovor bo‘lgan talabalar",

    ],
];
